CREATE DATABASE EXAMEN_SALMA;

USE  EXAMEN_SALMA;

CREATE TABLE Oferta(
id_oferta INT PRIMARY KEY AUTO_INCREMENT,
nombre_oferta VARCHAR(30) NOT NULL,
fecha_publicacion VARCHAR(20) NOT NULL,
prioridad VARCHAR(40) NOT NULL,
hiperenlace VARCHAR(50) NOT NULL,
descripcion VARCHAR(300) NOT NULL,
precio DOUBLE(5,2) NOT NULL);

SHOW TABLES;

SELECT * FROM Oferta;